### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by andre8359**
- Remove unnecessary files
- Add gitignore
- Change #ifdef for #pragma once
- Rename solution: "Projetc 4" -> "ComputerVisionTool"

### CODE REVIEW

**Comment by rrmhearts** [comment]
Does it build on your machine?

**Comment by andre8359** [comment]
Yep

**Comment by andre8359** [comment]
Yep

**Comment by rrmhearts** [comment]
I accept. Mainly because I haven't built it since grad school! Excited to know it still works. Thanks for contributing!

**Pull request merged**
